services:
  expense-tracker:
    container_name: expense-tracker
    ports:
      - '8080:8080'
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_NAME}
      PGUSER: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 5s
      timeout: 5s
      retries: 5
