db:
  name: jwt_expense_tracker
  host: localhost

spring:
  config:
    import: optional:secrets.yaml
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:${db.host}}:5432/${POSTGRES_DB:${db.name}}
    username: ${POSTGRES_USER:${db.name}}
    password: ${POSTGRES_PASSWORD:${db.password}}
